import { AlertTriangle, Flame, Info } from "lucide-react";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-neutral-100 font-sans text-black selection:bg-red-600 selection:text-white">
      {/* Header */}
      <header className="fixed w-full top-0 z-50 border-b-4 border-black bg-white p-4 flex justify-between items-center shadow-lg">
        <Link href="/sites/jerkstore" className="flex items-center gap-2 group">
          <Flame className="w-8 h-8 stroke-[3px] text-red-600 fill-yellow-400 group-hover:scale-110 transition-transform" />
          <h1 className="text-2xl font-black uppercase tracking-tighter italic">Jerkstore</h1>
        </Link>
        <Link href="/sites/jerkstore" className="px-4 py-2 bg-black text-white font-bold uppercase hover:bg-neutral-800 transition-colors border-2 border-neutral-600">
          Back to Safety
        </Link>
      </header>

      <main className="pt-32 pb-20 px-4 md:px-8">
        <div className="max-w-4xl mx-auto bg-white border-8 border-black shadow-[16px_16px_0px_0px_rgba(0,0,0,1)] p-8 md:p-12 relative overflow-hidden">
          {/* Background Texture */}
          <div className="absolute top-0 left-0 w-full h-full opacity-5 pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/noise.png')]"></div>

          <div className="relative z-10">
            <div className="flex items-center gap-4 mb-8 border-b-4 border-black pb-6">
              <AlertTriangle className="w-16 h-16 text-red-600" />
              <h1 className="text-4xl md:text-6xl font-black uppercase tracking-tighter">Terms of Emotional Damage</h1>
            </div>

            <div className="prose prose-xl prose-headings:font-black prose-headings:uppercase prose-p:font-mono prose-p:font-bold prose-strong:text-red-600 max-w-none">

              <div className="bg-yellow-300 border-4 border-black p-6 mb-8 -rotate-1 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <h2 className="text-2xl m-0 mb-2">🚨 Liability Disclaimer</h2>
                <p className="m-0 text-sm md:text-base">
                  By using this website, you agree that you are trash. Just kidding. (Kind of).
                  Jerkstore is a generative AI experiment designed for entertainment purposes only.
                  If you take anything this bot says seriously, that is a <strong>YOU problem</strong>, not an US problem.
                </p>
              </div>

              <h3>1. We Are Not Responsible For Your Feelings</h3>
              <p>
                This AI is trained to be mean, but funny. It is designed to simulate a roast battle, not a hate crime.
                It does not reflect the views of the creators, the hosting provider, or decent society.
                If you get roasted and cry, do not email us. We will frame your email and laugh at it.
              </p>

              <h3>2. Zero Tolerance for Hate Speech</h3>
              <p>
                We have strict constraints against genuine hate speech, racism, and bigotry.
                If the AI slips up (because LLMs are chaotic), that is a bug, not a feature.
                There is a difference between roasting your friend Dave about his receding hairline and actual cyberbullying.
              </p>

              <h3>3. Suicide & Self-Harm</h3>
              <p>
                We hate to see it. If you or someone you know is struggling, <strong>Jerkstore is not the place for you.</strong>
                Please seek professional help. The world is better with you in it, even if our AI says you look like a damp sock.
                <br />
                <a href="https://988lifeline.org/" className="text-blue-600 underline hover:bg-blue-100 px-1 inline-block mt-2">Call 988 (USA)</a> or your local emergency number.
              </p>

              <h3>4. Content Generation</h3>
              <p>
                The insults are generated by a Large Language Model. We do not manually curate every output.
                Occasionally, it might say something truly unhinged or cross a line we didn't intend.
                Again, <strong>no responsibility.</strong> You clicked the button. You asked for the smoke.
              </p>

              <h3>5. Data Collection</h3>
              <p>
                We collect nothing locally other than a flag to know you passed the age gate.
                We don't want your data. We barely want you here.
              </p>

              <div className="border-t-4 border-black mt-12 pt-8 text-center">
                <p className="text-sm text-neutral-500 uppercase">
                  Last Updated: The day we decided to choose violence.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
