export const BUTTON_LABELS = [
  "Roast it, Broseph",
  "Destroy Me, No Cap",
  "Circle Back to My Failures",
  "Leverage My Insecurities",
  "SKIBIDI TOILET (REVERSE)",
  "Touch Grass, Then Roast",
  "Ratio This Man",
  "Financial Ruin Awaits",
  "Psychic Attack: INITIATE",
  "Negative Aura Detection",
  "Skill Issue Verified",
  "Slay Me (Legally)",
  "Main Character Syndrome",
  "Fanum Tax My Self-Esteem",
  "Gaslight Me, King",
  "Cancel Me Harder",
  "NPC Energy Detected",
  "I'm the Problem, It's Me",
  "Corporate Synergy: PAIN",
  "End My Career",
  "Humiliate Me for $5",
  "Nepo Baby Verification",
  "It's Giving Mid",
  "Caught in 8K (HDR)",
  "Rent Free in My Head",
  "Mewing Until Roasted",
  "Boomer Cringe Alert",
  "Toxic Trait Checker",
  "Unsubscribe from Sanity",
  "Harder, AI Daddy"
];

export const TOPIC_LABELS = [
  "Topic to Roast",
  "Target for Elimination",
  "Victim Name",
  "Subject of Failure",
  "Who's Catching These Hands?",
  "Identity to Deconstruct",
  "Ego to Deflate",
  "Your Mid Friend's Name",
  "Corporate Entity to Slander",
  "Self-Sabotage Subject",
  "Roast Recipient",
  "Future Therapist's Notes",
  "Entry for the Burn Book",
  "Negative Aura Source",
  "Skill Issue Candidate",
  "NPC Designated for Roasting",
  "Chief Failure Officer",
  "Main Character to Cancel",
  "Source of Chronic Cringe",
  "Input for Aggression",
  "Who Hurt You?",
  "Roast Material",
  "Psychological Target",
  "Mid Take Provocation",
  "L + Ratio Recipient",
  "Victim of Logic",
  "Delulu Patient Zero",
  "Rent Free Tenant",
  "Bore-ish Behavior Source",
  "Desiccated Soul ID"
];
