"use client";

import { cn } from "@/lib/utils";

interface BOMItem {
  item: string;
  description: string;
  cost: string;
  source: string;
}

interface EstimateData {
  proposal: string;
  bom: BOMItem[];
  totalCost: string;
}

interface EstimateDisplayProps {
  data: EstimateData | null;
  isLoading: boolean;
  level: number;
}

import { PLANS } from "@overmake/constants";

export function EstimateDisplay({ data, isLoading, level }: EstimateDisplayProps) {
  if (isLoading) {
    return (
      <div className="animate-pulse space-y-4 p-8 border border-gray-200 rounded-lg">
        <div className="h-4 bg-gray-200 rounded w-3/4"></div>
        <div className="h-4 bg-gray-200 rounded w-1/2"></div>
        <div className="h-4 bg-gray-200 rounded w-5/6"></div>
      </div>
    );
  }

  if (!data) return null;

  const isLuxury = level > PLANS.DIYER.maxLevel;
  const isTrash = level <= PLANS.BUSHFIX.maxLevel;

  return (
    <div className={cn("mt-12 space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700",
      isLuxury && "font-serif",
      isTrash && "font-mono",
      !isLuxury && !isTrash && "font-sans"
    )}>

      <div className={cn("p-8 rounded-lg shadow-lg",
        isLuxury && "bg-black text-white border-2 border-gold-500",
        isTrash && "bg-yellow-100 text-red-800 border-4 border-dashed border-red-500 transform rotate-1",
        !isLuxury && !isTrash && "bg-white border border-gray-300"
      )}>
        <h2 className="text-3xl font-bold mb-6 uppercase tracking-widest border-b pb-4 border-current">
          {isLuxury ? "Executive Summary" : isTrash ? "The Plan" : "Proposal"}
        </h2>
        <div className="whitespace-pre-wrap leading-relaxed text-lg">
          {data.proposal}
        </div>
      </div>

      <div className={cn("p-8 rounded-lg shadow-lg",
        isLuxury && "bg-neutral-900 text-gold-300 border border-gold-500",
        isTrash && "bg-gray-100 text-black border-2 border-black",
        !isLuxury && !isTrash && "bg-gray-50 border border-gray-200"
      )}>
        <h3 className="text-2xl font-bold mb-6 uppercase tracking-widest border-b pb-2 border-current flex justify-between items-center">
          <span>Bill of Materials</span>
          <span className="text-sm opacity-70">CONFIDENTIAL</span>
        </h3>

        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-current opacity-50 text-xs uppercase tracking-wider">
              <th className="py-2">Item</th>
              <th className="py-2">Source</th>
              <th className="py-2 text-right">Cost</th>
            </tr>
          </thead>
          <tbody>
            {data.bom.map((item, idx) => (
              <tr key={idx} className="border-b border-white/10 last:border-0 hover:bg-white/5 transition-colors">
                <td className="py-4 pr-4 align-top">
                  <div className="font-bold">{item.item}</div>
                  <div className="text-sm opacity-70 mt-1">{item.description}</div>
                </td>
                <td className="py-4 pr-4 align-top text-sm italic">{item.source}</td>
                <td className="py-4 align-top text-right font-mono">{item.cost}</td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="border-t-2 border-current text-xl font-bold">
              <td colSpan={2} className="py-4 text-right">Total Estimated Cost:</td>
              <td className="py-4 text-right text-green-500">{data.totalCost}</td>
            </tr>
          </tfoot>
        </table>
      </div>

      <div className="text-center text-xs opacity-50 uppercase tracking-widest mt-12">
        Generated by Overmake Engine v1.0
      </div>

    </div>
  );
}
